# Generated by Django 5.2 on 2025-04-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='ban_image',
            new_name='image',
        ),
    ]
