# Generated by Django 5.2 on 2025-04-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_ban_image_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.AddField(
            model_name='banner',
            name='ban_images',
            field=models.ImageField(null=True, upload_to='photos/banner'),
        ),
    ]
