# Generated by Django 5.2 on 2025-04-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_banner_image_banner_ban_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_id', models.CharField(blank=True, max_length=250, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
