# Generated by Django 5.2.7 on 2025-10-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mtehod',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE', 'Online payment')], default='COD', max_length=20),
        ),
    ]
