# Generated by Django 5.2.7 on 2025-10-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_order_payment_mtehod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_mtehod',
            new_name='payment_method',
        ),
    ]
